all: true
with-expecter: false
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "{{.InterfaceName}}Mock"

packages:
  github.com/i4erkasov/go-pgsql:
    config:
      dir: "./pgx"
      outpkg: "pgx"
      mockname: "{{.InterfaceName}}"
      filename: "{{.InterfaceName | snakecase}}.go"
    interfaces:
      TxMock:
      RowMock:
  github.com/i4erkasov/go-pgsql/pgx:
    config:
      dir: "./pgx"
